/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { RewardNFT } from "./RewardNFT";
export type { StableVault } from "./StableVault";
export type { Stablecoin } from "./Stablecoin";
export type { VaultManager } from "./VaultManager";
